# Generated by Django 5.1.3 on 2024-12-05 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Company name", max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="FamilyMembers",
            fields=[
                ("member_id", models.IntegerField(primary_key=True, serialize=False)),
                ("status", models.CharField(max_length=50)),
                ("member_name", models.CharField(max_length=30)),
                ("birthday", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="GoodTypes",
            fields=[
                (
                    "good_type_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("good_type_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Passenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Passenger in trip", max_length=30),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reservations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("price", models.IntegerField()),
                ("total", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Rooms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("home_type", models.CharField(max_length=30)),
                ("address", models.CharField(max_length=50)),
                ("has_tv", models.BooleanField()),
                ("has_internet", models.BooleanField()),
                ("has_kitchen", models.BooleanField()),
                ("has_air_con", models.BooleanField()),
                ("price", models.IntegerField()),
                ("latitude", models.FloatField()),
                ("longnitude", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("middle_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("birthday", models.DateField()),
                ("address", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("middle_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Timepair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_pair", models.TimeField()),
                ("end_pair", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("email_verified_at", models.DateTimeField()),
                ("password", models.CharField(max_length=70)),
                ("phone_number", models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name="Goods",
            fields=[
                ("good_id", models.IntegerField(primary_key=True, serialize=False)),
                ("good_name", models.CharField(max_length=50)),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="firstapp.goodtypes",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payments",
            fields=[
                ("payment_id", models.IntegerField(primary_key=True, serialize=False)),
                ("amount", models.IntegerField()),
                ("unit_price", models.IntegerField()),
                ("date", models.DateTimeField()),
                (
                    "family_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="firstapp.familymembers",
                    ),
                ),
                (
                    "good",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="firstapp.goods"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField()),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="firstapp.reservations",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="reservations",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="firstapp.rooms"
            ),
        ),
        migrations.CreateModel(
            name="Student_In_Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "klass",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="firstapp.class"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="firstapp.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("classroom", models.IntegerField()),
                (
                    "klass",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="firstapp.class",
                        verbose_name="class",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="firstapp.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="firstapp.teacher",
                    ),
                ),
                (
                    "number_pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="firstapp.timepair",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                ("id_trip", models.IntegerField(primary_key=True, serialize=False)),
                ("plane", models.CharField(help_text="plane", max_length=30)),
                (
                    "town_from",
                    models.CharField(help_text="Input town from", max_length=30),
                ),
                ("town_to", models.CharField(help_text="Input town to", max_length=30)),
                ("time_out", models.DateTimeField()),
                ("time_in", models.DateTimeField()),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company name",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="firstapp.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pass_in_trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(help_text="Place client", max_length=5)),
                (
                    "passenger",
                    models.ForeignKey(
                        help_text="Input passenger",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="firstapp.passenger",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        help_text="Input trip id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="firstapp.trip",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="rooms",
            name="owner_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="firstapp.users"
            ),
        ),
        migrations.AddField(
            model_name="reservations",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="firstapp.users"
            ),
        ),
    ]
