# Generated by Django 5.1.3 on 2024-12-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assignment_name", models.CharField(max_length=500)),
                ("complexity", models.CharField(max_length=20)),
                ("name_table", models.CharField(max_length=20)),
            ],
        ),
    ]
