# Generated by Django 5.1.3 on 2025-04-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0003_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=255)),
            ],
        ),
    ]
